version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      steam:
        patterns:
          - "steam-user"
          - "steam-session"
          - "globaloffensive"
          - "cs2-inventory-resolver"
      vue:
        patterns:
          - "vue"
          - "vue-router"
          - "vue-tsc"
          - "@vueuse/*"
          - "@nuxt/*"
          - "eslint-plugin-vue"
          - "@vitejs/plugin-vue"
      electron:
        patterns:
          - "electron"
          - "electron-builder"
          - "electron-updater"
          - "electron-devtools-installer"
          - "@app/electron-versions"
      linting:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "prettier"
          - "typescript-eslint"
      build-tools:
        patterns:
          - "vite"
          - "typescript"
